config/routes.rb
Website::Application.routes.draw do
  root :to => 'homepage#index'
  
  match '/email_submit', to: "homepage#email_submit", as: 'email_submit'
end

app/models/email.rb
class Email < ActiveRecord::Base
  validates_presence_of :email  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    @quotes = QUOTES.map do |q|
      quote, author = q.split("--")
      { quote: quote.strip, author: author.strip }
    end
  
    @left_quotes, @right_quotes = @quotes.each_slice(QUOTES.size / 2).to_a
  end

  def email_submit
    if params['email_address']
      Email.create(:email => params[:email_address], :ip_address => request.remote_ip)
    end

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # generate CSS class names as controller-<controller> and action-<controller>-<action>
  # for controller and method scoped CSS
  def controller_method_css_class
    "controller-#{controller.controller_path.sub('/', '_')} action-#{controller.controller_path.sub('/', '_')}-#{controller.action_name}"
  end  
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/homepage/email_submit.js.erb
$("#email-modal").modal('hide')

app/views/homepage/index.html.erb
<div class='hero-unit'>

  <div class='logo-spotlights'>
    <%= image_tag 'radial light.png', class: 'radial-light' %>
    <%= image_tag 'spotlights.png', class: 'spotlights' %>
    <%= image_tag 'logo.png' %>
  </div>

  <h2>TV Advertising for the connected experience</h2>

</div>

<div class='hr'>
  <%= image_tag 'hr.png' %>
</div>

<div class='content'>
  <h1>Curious about the Future of TV?</h1>

  <div class='row'>
    <div class='span-one-third quote-image'>
      <%= image_tag 'quote.png' %>
    </div>

    <div class='span-one-third'>
      <%= image_tag "twitter.png" %>
    </div>

    <div class='span-one-third quote-image'>
      <%= image_tag 'quote.png' %>
    </div>

  </div>

  <div class='row'>
    <div class='span-one-third'>
      <ul class='quotes'>
        <% @left_quotes.each do |quote| %>
        <li>
          <p><%= quote[:quote] %></p>

          <div class='quoted'>
            <%= quote[:author] %>
          </div>          
        </li>
        <% end %>
      </ul>
    </div>

    <div class='span-one-third contact-info'>
      <span class='twitter-user'><%= link_to "@AdTonik", "http://twitter.com/adtonik"%></span>

      <button class='orange button' data-controls-modal="email-modal" data-keyboard="true" data-backdrop="true">Contact Us</button>
    </div>

    <div class='span-one-third'>
      <ul class='quotes'>
        <% @right_quotes.each do |quote| %>
        <li>
          <p><%= quote[:quote] %></p>

          <div class='quoted'>
            <%= quote[:author] %>
          </div>          
        </li>
        <% end %>
      </ul>      
    </div>
  </div>
</div>

<div id='email-modal' class='modal hide fade in' style='display: none'>

  <div class='modal-header'>
    <a href='#' class='close'>×</a>
    <h3>Curious about the future of TV?</h3>
  </div>

  <%= form_for :email, :url => email_submit_path, :remote => true do |f| %>
    <div class='modal-body'>
      <fieldset>
        <label for='email_address'>Email Address</label>
        <div class='input'>
          <input class='xlarge' id='email_address' name='email_address' size='30' type='text'>
        </div>
      </fieldset>
    </div>

    <div class='modal-footer'>
      <input type='submit' class='btn secondary' value='Submit'>
    </div>
  <% end %>
</div>

<script>

$(function() {  
  $('ul.quotes').quote_rotator({randomize_first_quote: true, rotation_speed: 7000});
});

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AdTonik - TV Advertising for the connected experience</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class='container <%= controller_method_css_class %>'>
  <%= yield %>
</div>

</body>
</html>